gcloud run deploy galaxy-sandbox-online ^
--project game-jams ^
--concurrency 50 ^
--max-instances 1 ^
--source F:\dev\game\unity\GalaxySandboxOnline\Server ^
--region us-central1 ^
--set-env-vars "MAX_BODIES=512" ^
--set-env-vars "MAX_CLIENTS=50" ^
--set-env-vars "MAX_VELOCITY=50" ^
--set-env-vars "MAX_BOUNDS=100" ^
--set-env-vars "GRAVITY=5" ^
--set-env-vars "TIME_SCALE=2" ^
--set-env-vars "MASS_SCALE=1.25" ^
--set-env-vars "DAMP_SCALE=1.15"